export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
